language: ruby
rvm:
  - 2.5
script:
  - gem build cfhighlander.gemspec
  - gem install cfhighlander-*.gem
  - which cfhighlander && cfhighlander help
  - cfndsl -u 2.19.0 && bundle exec rspec
deploy:
  provider: rubygems
  api_key: "${RUBYGEMS_API_KEY}"
  on:
   all_branches: true
   condition: $TRAVIS_BRANCH =~ ^develop|master &&  $TRAVIS_EVENT_TYPE =~ ^push|api$ && $TRAVIS_REPO_SLUG == "theonestack/cfhighlander"
